Abstract Discipline
LuizFelipeM/Logan pull request #26
Opened 2020-09-24 03:30 UTC by LuscasDaniel

2020-09-24 15:58 UTC, LuizFelipeM commented on backend/src/controllers/calendarController.ts
> +import { Router, Request, Response } from 'express'
pq esse arquivo foi adicionado?

2020-09-24 15:58 UTC, LuizFelipeM commented on backend/src/controllers/campusController.ts
> +import { Router, Request, Response } from 'express'
pq esse arquivo foi adicionado também?

2020-09-24 15:58 UTC, LuizFelipeM commented on backend/src/controllers/courseController.ts
> +import { Router, Request, Response } from 'express'
pq esse arquivo foi adicionado também?

2020-09-24 15:58 UTC, LuizFelipeM commented on backend/src/repositories/courseRepository.ts
> +import { coursesTable } from '../database/common/coursesTable'
pq esse arquivo foi adicionado também?

2020-09-24 15:58 UTC, LuizFelipeM commented on backend/src/services/courseService.ts
> +import { ICourse } from '../domain/interfaces/entities/ICourse'
pq esse arquivo foi adicionado também?

2020-09-24 15:58 UTC, LuizFelipeM commented on backend/src/services/noteFoulsService.ts
> +  ) { super() }// needs mapper to complete
o mapper é de quais entidades? ele é pra os filtros?

2020-09-28 03:08 UTC, LuizFelipeM requested changes

2020-09-28 03:08 UTC, LuizFelipeM commented on backend/src/domain/interfaces/entities/ISemester.ts
> +    evalP1Start: number,
essas props são strings

2020-10-01 00:32 UTC, LuscasDaniel commented on backend/src/services/noteFoulsService.ts
> +  ) { super() }// needs mapper to complete
Para os filtros da noteFouls, eu havia conversado com você os mapper e adicionar ai ficaria interessante aparentemente facilitaria os filtros, ainda não testei

2020-10-01 00:37 UTC, merged