Discipline FIlter
LuizFelipeM/Logan pull request #31
Opened 2020-10-03 06:30 UTC by LuscasDaniel

2020-10-04 23:28 UTC, PedroRicciardi commented on backend/src/services/disciplineService.ts
> +    console.log(disciplines)
Pode deletar essa linha

2020-10-08 22:11 UTC, LuizFelipeM requested changes

2020-10-08 22:11 UTC, LuizFelipeM commented on backend/src/controllers/disciplineController.ts
> +  // private async getTypeWorkload () {
remove os comentários

2020-10-08 22:11 UTC, LuizFelipeM commented on backend/src/domain/mappers/DisciplineMapper.ts
> +export function toTypeAndWorkload (data: IDiscipline, typeDiscipline: ITypeDiscipline | undefined): ITypeAndWorkloadDto {
Esse nome e o nome da Dto estão estranhos, não estão representando bem.
Tipo, se você for ler fica "type do que?"

2020-10-08 22:11 UTC, LuizFelipeM commented on backend/src/repositories/coursesRepository.ts
> +   selectAllCourseDto = async (): Promise<ICourseDto[]> => await knex(this.table)
ainda ta usando?

2020-10-08 22:11 UTC, LuizFelipeM commented on backend/src/repositories/disciplineRepository.ts
> +  getDisciplineName = async () :Promise<IDiscipline[]> => knex(this.table)
remove o async

2020-10-22 01:01 UTC, LuizFelipeM approved these changes

2020-10-22 01:02 UTC, merged